repos:
- repo: local
  hooks:
    - id: ruff lint
      name: ruff lint
      entry: hatch run lint:ruff check
      language: system
      types: [python]
    - id: ruff format
      name: ruff format
      entry: hatch run lint:ruff format
      language: system
      types: [python]
    - id: mypy
      name: mypy
      entry: hatch run dev:mypy
      language: system
      types: [python]
      exclude: ^(tests/|playground/|examples/|benchmarks/)
