repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.230'
  hooks:
    - id: ruff
- repo: https://github.com/python/black.git
  rev: 22.6.0
  hooks:
    - id: black
      language_version: python3.10
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: poetry run mypy
      types:
        - "python"
      language: python
      exclude: ^(tests|benchmarks|examples)/
      args: ["--strict"]
