repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.29
    hooks:
      - id: uv-lock
      - id: uv-export

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: just lint
        language: system
        types: [python]
