repos:
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      language_version: python3.10
- repo: https://github.com/PyCQA/autoflake
  rev: "v1.4"
  hooks:
    - id: autoflake
      language_version: python3.10
      args: ["-i"]
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/python/black.git
  rev: 22.6.0
  hooks:
    - id: black
      language_version: python3.10
