from _typeshed import Incomplete

class Cell:
    x: Incomplete
    y: Incomplete
    h: Incomplete
    centroid: Incomplete
    distance: Incomplete
    max_distance: Incomplete
    def __init__(self, x, y, h, polygon) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

def polylabel(polygon, tolerance: float = ...): ...
