from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _check_out_array(*args, **kwargs) -> Any: ...
def _geom_factory(*args, **kwargs) -> Any: ...
def collections_1d(*args, **kwargs) -> Any: ...
def get_parts(*args, **kwargs) -> Any: ...
def simple_geometries_1d(*args, **kwargs) -> Any: ...
