def affine_transform(geom, matrix): ...
def rotate(geom, angle, origin: str = ..., use_radians: bool = ...): ...
def scale(
    geom, xfact: float = ..., yfact: float = ..., zfact: float = ..., origin: str = ...
): ...
def skew(
    geom, xs: float = ..., ys: float = ..., origin: str = ..., use_radians: bool = ...
): ...
def translate(geom, xoff: float = ..., yoff: float = ..., zoff: float = ...): ...
