from _typeshed import Incomplete

class CoordinateSequence:
    def __init__(self, coords) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __getitem__(self, key): ...
    def __array__(self, dtype: Incomplete | None = ...): ...
    @property
    def xy(self): ...
