def transform(geometry, transformation, include_z: bool = ...): ...
def count_coordinates(geometry): ...
def get_coordinates(geometry, include_z: bool = ..., return_index: bool = ...): ...
def set_coordinates(geometry, coordinates): ...
