from shapely.lib import GEOSException as GEOSException, ShapelyError

def setup_signal_checks(interval: int = ...) -> None: ...

class UnsupportedGEOSVersionError(ShapelyError): ...
class DimensionError(ShapelyError): ...
class TopologicalError(ShapelyError): ...
class ShapelyDeprecationWarning(FutureWarning): ...
class EmptyPartError(ShapelyError): ...
class GeometryTypeError(ShapelyError): ...

def __getattr__(name): ...
