def line_interpolate_point(line, distance, normalized: bool = ..., **kwargs): ...
def line_locate_point(line, other, normalized: bool = ..., **kwargs): ...
def line_merge(line, directed: bool = ..., **kwargs): ...
def shared_paths(a, b, **kwargs): ...
def shortest_line(a, b, **kwargs): ...
