from _typeshed import Incomplete

def area(geometry, **kwargs): ...
def distance(a, b, **kwargs): ...
def bounds(geometry, **kwargs): ...
def total_bounds(geometry, **kwargs): ...
def length(geometry, **kwargs): ...
def hausdorff_distance(a, b, densify: Incomplete | None = ..., **kwargs): ...
def frechet_distance(a, b, densify: Incomplete | None = ..., **kwargs): ...
def minimum_clearance(geometry, **kwargs): ...
def minimum_bounding_radius(geometry, **kwargs): ...
