from _typeshed import Incomplete

class PreparedGeometry:
    context: Incomplete
    prepared: bool
    def __init__(self, context) -> None: ...
    def contains(self, other): ...
    def contains_properly(self, other): ...
    def covers(self, other): ...
    def crosses(self, other): ...
    def disjoint(self, other): ...
    def intersects(self, other): ...
    def overlaps(self, other): ...
    def touches(self, other): ...
    def within(self, other): ...
    def __reduce__(self) -> None: ...

def prep(ob): ...
