from _typeshed import Incomplete

def difference(a, b, grid_size: Incomplete | None = ..., **kwargs): ...
def intersection(a, b, grid_size: Incomplete | None = ..., **kwargs): ...
def intersection_all(geometries, axis: Incomplete | None = ..., **kwargs): ...
def symmetric_difference(a, b, grid_size: Incomplete | None = ..., **kwargs): ...
def symmetric_difference_all(geometries, axis: Incomplete | None = ..., **kwargs): ...
def union(a, b, grid_size: Incomplete | None = ..., **kwargs): ...
def union_all(
    geometries,
    grid_size: Incomplete | None = ...,
    axis: Incomplete | None = ...,
    **kwargs,
): ...

unary_union = union_all

def coverage_union(a, b, **kwargs): ...
def coverage_union_all(geometries, axis: Incomplete | None = ..., **kwargs): ...
