name: Deploy Documents

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - id: cache-rust
        name: cache rust
        uses: Swatinem/rust-cache@v2

      - run: cargo install rustfilt coverage-prepare
        if: steps.cache-rust.outputs.cache-hit != 'true'

      - run: rustup component add llvm-tools-preview

      - name: install uv
        uses: astral-sh/setup-uv@v5

      - name: install deps
        run: uv sync --group docs --all-extras

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
