# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Lint & Test"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Setup rye
        id: setup-rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
      - name : Run linting
        run: ruff check
      - name : Run formatting
        run: ruff format --check
      - name: Run mypy
        run: mypy netext
      - name: Test with pytest
        run: pytest --cov=netext --cov-report=xml:coverage.xml
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          verbose: true # optional (default = false)
