# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Lint & Test"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup rye
        id: setup-rye
        uses: eifinger/setup-rye@v2
        with:
          cache-prefix: 'py3.10'
          enable-cache: true
      - name: Sync
        run: |
          touch $RYE_HOME/config.toml
          rye config --set-bool behavior.use-uv=true
          rye sync
      - name: Activate virtualenv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name : Run linting
        run: rye lint
      - name : Run formatting
        run: rye fmt
      - name: Run mypy
        run: pyright netext
      - name: Test with pytest
        run: pytest --cov=netext --cov-report=xml:coverage.xml
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          verbose: true # optional (default = false)
