name: "Publish on Release"

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install Pipx
        run: |
          pip install --upgrade pip
          python3.12 -m pip install --user pipx
          python3.12 -m pipx ensurepath
      - name: Install Hatch
        run: |
          pipx install hatch
          hatch config set dirs.env.virtual .hatch
          hatch env create lint
      - name: Cache hatch virtualenvs
        uses: actions/cache@v2
        id: cache
        with:
          path: .hatch
          key: ubuntu-latest-hatch-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ubuntu-latest-hatch-${{ hashFiles('pyproject.toml') }}
      - name: Build
        run: |
          hatch build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
